---

- hosts: all
  become: true
  tasks:

  - name: install apache2 package with php support for Ubuntu servers
    package:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php for AlmaLinux servers
      dnf:
        name:
          - httpd
          - php
        state: latest
        update_cache: yes
      when: ansible_distribution == "AlmaLinux"
