---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (AlmaLinux)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "AlmaLinux"

  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:

  - name: install apache2 package with php support for Ubuntu servers
    tags: ubuntu,apache2,apache
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install httpd and php for AlmaLinux servers
    tags: apache,httpd,almalinux
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "AlmaLinux"

  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (AlmaLinux)
    tags: db,mariadb,almalinux
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "AlmaLinux"

  - name: install mariadb package (Ubuntu)
    tags: db,mariadb,ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"


- hosts: file_servers
  become: true
  tasks:

  - name: install samba package (same for AlmaLinux and Ubuntu)
    tags: samba
    package:
      name: samba
      state: latest
